apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-istio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rancher/charts.git
    targetRevision: dev-v2.6
    path: charts/rancher-istio/100.3.0+up1.13.3
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    syncOptions: 
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
