apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-monitoring-crd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.rancher.io/
    chart: rancher-monitoring-crd
    targetRevision: 100.0.0+up16.6.0
    helm:
      releaseName: rancher-charts
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-monitoring-system
  syncPolicy:
    syncOptions: 
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
